### ISSUE TITLE
[Icon] Logo proposal for File Android Manager

### ISSUE THREAD

**Issue by mendezand** [Mercandj/file-android#1]
Hi.
When I did not see that there was a logo, I decided to make a contribution.
You can request the changes you want, once approved I will send the editable files.
![image](https://user-images.githubusercontent.com/38763253/39713542-1cc9e864-51f5-11e8-9c07-5236800bf278.png)

**Comment by Mercandj** [comment]
Hi,

Thank you a lot for your contribution to this project! I really appreciate that, and like the fact that your proposition respects **material design**. (respect the Android guidelines matters to me 😄)
Unfortunately, this project is the new version of this [old application](https://github.com/Mercandj/FileSpace-Android) that already have an icon.
Indeed, it's could be good to have a new icon. So I started a new one that respect [adaptive icons guideline.](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) (on Android, new versions of the OS support icons that could take the shape that the user select: square, rounded square, squircle, treadrop...) 

With that in mind, I design a first version [here](https://github.com/Mercandj/file-android/tree/master/app/src/main/res/common). You can see on the left of this screenshot old version of the icon (non adaptive) and on the right the new version (adaptive):

<img width="423" alt="screen shot 2018-05-07 at 19 14 40" src="https://user-images.githubusercontent.com/3717316/39714642-01b1a9d2-522b-11e8-9b29-a48ed62e5c0b.png">

----

Regarding the [color codes of this application](https://github.com/Mercandj/file-android/blob/master/app/src/main/res/common/values/colors.xml), this app is more blue than green for now =)

Here, a first screenshot of the app:

<img width="825" alt="screen shot 2018-05-07 at 19 17 29" src="https://user-images.githubusercontent.com/3717316/39714811-7c3ed850-522b-11e8-9c44-4f4de79f5012.png">

----

To design adaptive icon, svg is great and icon should have a [foreground](https://github.com/Mercandj/file-android/blob/master/app/src/main/res/common/drawable-v24/ic_launcher_foreground.xml) and a [background](https://github.com/Mercandj/file-android/blob/master/app/src/main/res/common/drawable/ic_launcher_background.xml)

----

For these reasons, I will for now, still use the one that I have.
Again, thks a lot!

Kind regards,
Jonathan

**Comment by mendezand** [comment]
Thank you very much for all the knowledge you have given me. I am new at this. Excuse me if I do not understand something.

I made a change of colors and created a .SVG file. With the file you can do the tests or should I send it in .PNG image files as separate

![image](https://user-images.githubusercontent.com/38763253/39717920-b04130cc-5202-11e8-879a-2162b8debd76.png)

In case you do not like the design you can tell me. 😊

[SVG File](https://drive.google.com/file/d/1WTq29gg9U9oGx-WgBpAoWuFPKKOeeZLY/view?usp=sharing)

**Comment by Mercandj** [comment]
Nice, thanks a lot for your proposals. For now, I will keep the icon that I made in order to keep visual effect on drag and drop and to have explicit folder icon (your "hand" black icon does not give a sens/meaning to explain the app to the user, sorry for that)

PS: I mean this [drag and drop effect](
https://github.com/JakeWharton/SdkSearch/pull/51)
